name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - run: |
        chmod +x ./gradlew
        ./gradlew :app:assembleRelease
    - uses: actions/upload-artifact@v3
      with:
        name: libnative-lib.so
        path: /home/runner/work/Auto-Il2cppDumper/Auto-Il2cppDumper/app/build/intermediates/cmake/release/obj/armeabi-v7a/
